---
- name: Create dest directory
  ansible.builtin.file:
    path: "{{ host_dest_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ host_user }}"

- name: Create initial directories for applications
  ansible.builtin.file:
    path: "{{ host_dest_dir }}/{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ host_user }}"
  loop:
    - gitlab
    - mattermost
    - nginx
    - registry

- name: Create applications config directories
  ansible.builtin.file:
    path: "{{ host_dest_dir }}/{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ host_user }}"
  loop:
    - nginx/config
    - gitlab/config
    - gitlab/config/runner

- name: Copy gitlab docker-compose
  template:
    src: gitlab-docker-compose.yml.j2
    dest: "{{ host_dest_dir }}/gitlab/docker-compose.yml"
    owner: "{{ host_user }}"

- name: Copy gitlab runner conf
  template:
    src: gitlab-runner.toml.j2
    dest: "{{ host_dest_dir }}/gitlab/config/runner/config.toml"
    owner: "{{ host_user }}"

- name: Copy nginx docker-compose
  template:
    src: nginx-docker-compose.yml.j2
    dest: "{{ host_dest_dir }}/nginx/docker-compose.yml"
    owner: "{{ host_user }}"

- name: Copy nginx conf
  template:
    src: gitlab-nginx.conf.j2
    dest: "{{ host_dest_dir }}/nginx/config/gitlab.conf"
    owner: "{{ host_user }}"
