---
- name: Install docker and create Gitlab Instance
  hosts: all
  become: yes

  vars:
    user: ubuntu
    has_gitlab: "{{ gitlab | default('no') | bool }}"

  roles:
    - role: docker
      default_user: "{{ user }}"
      network: ubuntu

    - role: gitlab
      vars:
        host_user: "{{ user }}"
        gitlab_image_tag: "{{ gitlab_tag | default('15.3.0-ce.0')}}"
        gitlab_runner_image_tag: "{{ gitlab_runner_tag | default('alpine-v15.3.0') }}"
        nginx_image_tag: "{{ nginx_tag | default('1.23-alpine') }}"
      when: has_gitlab is true
